// Objective-C API for talking to testGomobile Go package.
//   gobind -lang=objc testGomobile
//
// File is generated by gobind. Do not edit.

#ifndef __TestGomobile_H__
#define __TestGomobile_H__

@import Foundation;
#include "Universe.objc.h"


@protocol TestGomobileObjeCCallback;
@class TestGomobileObjeCCallback;

@protocol TestGomobileObjeCCallback <NSObject>
- (void)oneMethod;
@end

FOUNDATION_EXPORT void TestGomobileCallObjC(void);

FOUNDATION_EXPORT void TestGomobileRegisterCallback(id<TestGomobileObjeCCallback> c);

@class TestGomobileObjeCCallback;

@interface TestGomobileObjeCCallback : NSObject <goSeqRefInterface, TestGomobileObjeCCallback> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (void)oneMethod;
@end

#endif
