
// Objective-C API for talking to the following Go packages
//
//	testGomobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __TestGomobile_FRAMEWORK_H__
#define __TestGomobile_FRAMEWORK_H__

#include "TestGomobile.objc.h"
#include "Universe.objc.h"

#endif
