// Objective-C API for talking to marshall Go package.
//   gobind -lang=objc marshall
//
// File is generated by gobind. Do not edit.

#ifndef __Marshall_H__
#define __Marshall_H__

@import Foundation;
#include "Universe.objc.h"


@class MarshallClient;
@class MarshallHub;
@protocol MarshallNativeClass;
@class MarshallNativeClass;

@protocol MarshallNativeClass <NSObject>
- (NSString*)getRootPath;
- (void)oneMethod;
@end

/**
 * Client is a middleman between the websocket connection and the hub.
 */
@interface MarshallClient : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
@end

/**
 * hub maintains the set of active clients and broadcasts messages to the
clients.
 */
@interface MarshallHub : NSObject <goSeqRefInterface> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (instancetype)init;
@end

@interface Marshall : NSObject
// skipped variable ENDPOINTS with unsupported type: *types.Map

+ (NSString*) rooT_PATH;
+ (void) setROOT_PATH:(NSString*)v;

@end

FOUNDATION_EXPORT void MarshallCheckError(NSError* err);

FOUNDATION_EXPORT void MarshallConfigure(id<MarshallNativeClass> class, NSData* initialState);

FOUNDATION_EXPORT NSString* MarshallGetPath(NSString* endpoint);

FOUNDATION_EXPORT BOOL MarshallInitializeStore(NSError** error);

FOUNDATION_EXPORT void MarshallListen(void);

FOUNDATION_EXPORT void MarshallRegisterCallback(id<MarshallNativeClass> class);

FOUNDATION_EXPORT void MarshallRiseStore(void);

FOUNDATION_EXPORT void MarshallRunServer(void);

FOUNDATION_EXPORT void MarshallSaveStore(void);

FOUNDATION_EXPORT void MarshallSetRootPath(NSString* path);

FOUNDATION_EXPORT void MarshallShowStore(void);

FOUNDATION_EXPORT void MarshallUpdateStore(NSString* valueType, NSString* key, NSString* value);

@class MarshallNativeClass;

@interface MarshallNativeClass : NSObject <goSeqRefInterface, MarshallNativeClass> {
}
@property(strong, readonly) id _ref;

- (instancetype)initWithRef:(id)ref;
- (NSString*)getRootPath;
- (void)oneMethod;
@end

#endif
