
// Objective-C API for talking to the following Go packages
//
//	marshall
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Marshall_FRAMEWORK_H__
#define __Marshall_FRAMEWORK_H__

#include "Marshall.objc.h"
#include "Universe.objc.h"

#endif
